hash-format = "sha256"

[[files]]
file = "config/bclib/client.json"

[[files]]
file = "config/bclib/server.json"

[[files]]
file = "config/builtinservers.json"

[[files]]
file = "config/collective/checked.txt"

[[files]]
file = "config/expanded_ecosphere/config.json5"

[[files]]
file = "mods/content/applied-energistics/ae2-qol-recipes.pw.toml"
metafile = true

[[files]]
file = "mods/content/applied-energistics/ae2.pw.toml"
metafile = true

[[files]]
file = "mods/content/applied-energistics/applied-energistics-2-wireless-terminals.pw.toml"
metafile = true

[[files]]
file = "mods/content/computer-craft/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/content/computer-craft/cccbridge.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/bellsandwhistles.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/copycats.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-dreams-and-desires.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-steam-n-rails.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-track-map.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/estrogen.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/interiors.pw.toml"
metafile = true

[[files]]
file = "mods/content/decoration/nightlights.pw.toml"
metafile = true

[[files]]
file = "mods/content/farmers-delight/farmers-delight-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/content/furniture/dramatic-doors.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/creeper-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/enderman-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/content/other/exposure.pw.toml"
metafile = true

[[files]]
file = "mods/content/other/mighty-mail-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/content/qol/mmmmmmmmmmmm.pw.toml"
metafile = true

[[files]]
file = "mods/content/qol/sleep-tight.pw.toml"
metafile = true

[[files]]
file = "mods/content/qol/straw-statues.pw.toml"
metafile = true

[[files]]
file = "mods/content/silly/moyai.pw.toml"
metafile = true

[[files]]
file = "mods/content/silly/mystical-oak-tree.pw.toml"
metafile = true

[[files]]
file = "mods/content/supplementaries/amendments.pw.toml"
metafile = true

[[files]]
file = "mods/content/supplementaries/supplementaries-squared.pw.toml"
metafile = true

[[files]]
file = "mods/content/supplementaries/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/emi/ae2-emi-crafting.pw.toml"
metafile = true

[[files]]
file = "mods/emi/emi.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/balm.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/bclib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/botarium.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/cicada.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/collective.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/completeconfig.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/coroutil.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/cristel-lib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/framework-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/fusion-connected-textures.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/jamlib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/midnightlib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/paxi.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/yungs-api.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/audio/plasmo-voice.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/audio/pv-addon-sculk.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/building/diagonal-fences.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/building/diagonal-walls.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/building/diagonal-windows.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/advancement-screenshot.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/armor-statues.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/cat_jam.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/companion.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/crawl.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/cut-through.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/do-a-barrel-roll.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/easy-anvils.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/easy-magic.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/grass-seeds.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/kleeslabs.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/netherportalfix.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/rightclickharvest.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/simple-cobblestone-generator.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/treechop.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/yigd.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/interface/auth-me.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/interface/better-advancements.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/interface/better-stats.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/interface/borderless-mining.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/interface/builtin-servers.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/interface/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/interface/ding.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/interface/disable-accessibility-screen.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/interface/language-reload.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/interface/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/interface/screenshot-to-clipboard.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/interface/seamless-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/interface/silent-screenshots.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/inventory/ae2-mousetweaks-fix.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/inventory/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/inventory/norecipebook-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/inventory/shulkerboxtooltip.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/performance/async-locator.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/performance/badoptimizations.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/performance/c2me-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/performance/clumps.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/performance/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/performance/fast-paintings.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/performance/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/performance/fix-gpu-memory-leak.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/performance/indium.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/performance/iris.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/performance/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/performance/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/performance/memoryleakfix.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/performance/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/performance/moreculling.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/performance/neruina.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/performance/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/performance/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/performance/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/performance/vmp-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/bobby.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/distinguished-potions.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/fabricbettergrass.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/fallingleaves.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/visuality.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/what-are-they-up-to.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/amplified-nether.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/betterend.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/betternether.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/expanded-ecosphere.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/flat-bedrock.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/nullscape.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/yungs/yungs-better-desert-temples.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/yungs/yungs-better-jungle-temples.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/yungs/yungs-better-nether-fortresses.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/yungs/yungs-better-ocean-monuments.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/yungs/yungs-better-strongholds.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/yungs/yungs-better-witch-huts.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
metafile = true
