hash-format = "sha256"

[[files]]
file = "config/bclib/client.json"

[[files]]
file = "config/bclib/server.json"

[[files]]
file = "config/paxi/datapack_load_order.json"

[[files]]
file = "config/paxi/datapacks/better-villages-bountiful.pw.toml"
metafile = true

[[files]]
file = "config/paxi/resourcepack_load_order.json"

[[files]]
file = "config/paxi/resourcepacks/advancement-plaques-with-vines.pw.toml"
metafile = true

[[files]]
file = "config/presencefootsteps/updater.json"

[[files]]
file = "mods/advancement-plaques.pw.toml"
metafile = true

[[files]]
file = "mods/ambient-environment.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/armor-statues.pw.toml"
metafile = true

[[files]]
file = "mods/axolotl-bucket-fix.pw.toml"
metafile = true

[[files]]
file = "mods/bclib.pw.toml"
metafile = true

[[files]]
file = "mods/beautify-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
metafile = true

[[files]]
file = "mods/better-village-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/betterend.pw.toml"
metafile = true

[[files]]
file = "mods/betternether.pw.toml"
metafile = true

[[files]]
file = "mods/block-runner.pw.toml"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
metafile = true

[[files]]
file = "mods/bountiful.pw.toml"
metafile = true

[[files]]
file = "mods/bushier-flowers.pw.toml"
metafile = true

[[files]]
file = "mods/carpeted-stairs.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
metafile = true

[[files]]
file = "mods/chefs-delight.pw.toml"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
metafile = true

[[files]]
file = "mods/companion.pw.toml"
metafile = true

[[files]]
file = "mods/connectible_chains.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/crawl.pw.toml"
metafile = true

[[files]]
file = "mods/create-fabric-sodium-fix.pw.toml"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
metafile = true

[[files]]
file = "mods/ct-overhaul-village.pw.toml"
metafile = true

[[files]]
file = "mods/ctov-beautify-compat.pw.toml"
metafile = true

[[files]]
file = "mods/ctov-chefs-delight-compat.pw.toml"
metafile = true

[[files]]
file = "mods/ctov-farmers-delight-compat.pw.toml"
metafile = true

[[files]]
file = "mods/ctov-friends-and-foes-compat.pw.toml"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/diagonal-fences.pw.toml"
metafile = true

[[files]]
file = "mods/diagonal-walls.pw.toml"
metafile = true

[[files]]
file = "mods/diagonal-windows.pw.toml"
metafile = true

[[files]]
file = "mods/distinguished-potions.pw.toml"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
metafile = true

[[files]]
file = "mods/easy-magic.pw.toml"
metafile = true

[[files]]
file = "mods/effect-descriptions.pw.toml"
metafile = true

[[files]]
file = "mods/ender-zoology.pw.toml"
metafile = true

[[files]]
file = "mods/etcetera.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/friends-and-foes.pw.toml"
metafile = true

[[files]]
file = "mods/grass-seeds.pw.toml"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/jade-addons-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
metafile = true

[[files]]
file = "mods/kambrik.pw.toml"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
metafile = true

[[files]]
file = "mods/library-ferret-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
metafile = true

[[files]]
file = "mods/magnum-torch.pw.toml"
metafile = true

[[files]]
file = "mods/mavapi.pw.toml"
metafile = true

[[files]]
file = "mods/mavm.pw.toml"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
metafile = true

[[files]]
file = "mods/mindful-darkness.pw.toml"
metafile = true

[[files]]
file = "mods/mmmmmmmmmmmm.pw.toml"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
metafile = true

[[files]]
file = "mods/moyai.pw.toml"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
metafile = true

[[files]]
file = "mods/mystical-oak-tree.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/norecipebook-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/opac-fabric-create-support.pw.toml"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
metafile = true

[[files]]
file = "mods/paxi.pw.toml"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
metafile = true

[[files]]
file = "mods/plasmo-voice.pw.toml"
metafile = true

[[files]]
file = "mods/plethora-peripherals.pw.toml"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/pv-addon-soundphysics.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
metafile = true

[[files]]
file = "mods/sleep-tight.pw.toml"
metafile = true

[[files]]
file = "mods/snow-under-trees-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/snowy-spirit.pw.toml"
metafile = true

[[files]]
file = "mods/snuffles-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/spyglass-astronomy.pw.toml"
metafile = true

[[files]]
file = "mods/spyglass-improvements.pw.toml"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
metafile = true

[[files]]
file = "mods/stoneworks.pw.toml"
metafile = true

[[files]]
file = "mods/straw-statues.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/thigh-highs-etc.pw.toml"
metafile = true

[[files]]
file = "mods/tiny-skeletons.pw.toml"
metafile = true

[[files]]
file = "mods/travelers-titles.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
metafile = true

[[files]]
file = "mods/vivecraft.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
metafile = true
