hash-format = "sha256"

[[files]]
file = "mods/content/applied-energistics/ae2-qol-recipes.pw.toml"
metafile = true

[[files]]
file = "mods/content/applied-energistics/ae2.pw.toml"
metafile = true

[[files]]
file = "mods/content/applied-energistics/applied-energistics-2-wireless-terminals.pw.toml"
metafile = true

[[files]]
file = "mods/content/applied-energistics/mega.pw.toml"
metafile = true

[[files]]
file = "mods/content/other/exposure.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/konkrete.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/melody.pw.toml"
metafile = true

[[files]]
file = "mods/performance/async-locator.pw.toml"
metafile = true

[[files]]
file = "mods/performance/bobby.pw.toml"
metafile = true

[[files]]
file = "mods/performance/c2me-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/performance/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/performance/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/performance/gputape.pw.toml"
metafile = true

[[files]]
file = "mods/performance/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/performance/indium.pw.toml"
metafile = true

[[files]]
file = "mods/performance/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/performance/language-reload.pw.toml"
metafile = true

[[files]]
file = "mods/performance/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/performance/memoryleakfix.pw.toml"
metafile = true

[[files]]
file = "mods/performance/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/performance/moreculling.pw.toml"
metafile = true

[[files]]
file = "mods/performance/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/performance/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/performance/vmp-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/auth-me.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/builtin-servers.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/disable-accessibility-screen.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/drippy-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/fancymenu.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/seamless-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/utilities/invview.pw.toml"
metafile = true

[[files]]
file = "mods/utilities/spark.pw.toml"
metafile = true

[[files]]
file = "mods/vivecraft.pw.toml"
metafile = true
