hash-format = "sha256"

[[files]]
file = "config/bclib/client.json"

[[files]]
file = "config/bclib/server.json"

[[files]]
file = "config/bluemap/core.conf"

[[files]]
file = "config/builtinservers.json"

[[files]]
file = "config/paxi/datapack_load_order.json"

[[files]]
file = "config/paxi/datapacks/better-villages-bountiful.pw.toml"
metafile = true

[[files]]
file = "config/paxi/resourcepack_load_order.json"

[[files]]
file = "config/paxi/resourcepacks/advancement-plaques-with-vines.pw.toml"
metafile = true

[[files]]
file = "config/paxi/resourcepacks/creeper-overhaul-overhaul.pw.toml"
metafile = true

[[files]]
file = "config/presencefootsteps/updater.json"

[[files]]
file = "modlist.md"

[[files]]
file = "mods/accelerated-decay.pw.toml"
metafile = true

[[files]]
file = "mods/additional-lanterns.pw.toml"
metafile = true

[[files]]
file = "mods/advancement-frames.pw.toml"
metafile = true

[[files]]
file = "mods/ae2-mousetweaks-fix.pw.toml"
metafile = true

[[files]]
file = "mods/ae2/ae2-emi-crafting.pw.toml"
metafile = true

[[files]]
file = "mods/ae2/ae2-qol-recipes.pw.toml"
metafile = true

[[files]]
file = "mods/ae2/ae2.pw.toml"
metafile = true

[[files]]
file = "mods/ae2/applied-energistics-2-wireless-terminals.pw.toml"
metafile = true

[[files]]
file = "mods/alloy-forgery.pw.toml"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
metafile = true

[[files]]
file = "mods/bettersmithingtable.pw.toml"
metafile = true

[[files]]
file = "mods/blahaj.pw.toml"
metafile = true

[[files]]
file = "mods/bluemap/bluemap-offline-player-markers-(fabric).pw.toml"
metafile = true

[[files]]
file = "mods/bluemap/bluemap-sign-markers.pw.toml"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
metafile = true

[[files]]
file = "mods/cat_jam.pw.toml"
metafile = true

[[files]]
file = "mods/charmonium.pw.toml"
metafile = true

[[files]]
file = "mods/completeconfig.pw.toml"
metafile = true

[[files]]
file = "mods/content/better-archeology.pw.toml"
metafile = true

[[files]]
file = "mods/content/bountiful.pw.toml"
metafile = true

[[files]]
file = "mods/content/building/another-furniture.pw.toml"
metafile = true

[[files]]
file = "mods/content/building/beautify-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/content/building/connectible_chains.pw.toml"
metafile = true

[[files]]
file = "mods/content/building/hearth-and-home.pw.toml"
metafile = true

[[files]]
file = "mods/content/building/nightlights.pw.toml"
metafile = true

[[files]]
file = "mods/content/building/stoneworks.pw.toml"
metafile = true

[[files]]
file = "mods/content/building/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/content/computers/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/content/computers/cccbridge.pw.toml"
metafile = true

[[files]]
file = "mods/content/computers/plethora-peripherals.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/bellsandwhistles.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/copycats.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-big-cannons.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-deco.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-fabric-sodium-fix.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-new-age.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-steam-n-rails.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-track-map.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/slice-and-dice.pw.toml"
metafile = true

[[files]]
file = "mods/content/food/chefs-delight.pw.toml"
metafile = true

[[files]]
file = "mods/content/food/farmers-delight-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/axolotl-bucket-fix.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/creeper-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/duckling.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/ender-zoology.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/enderman-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/friends-and-foes-flowery-mooblooms-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/friends-and-foes.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/hamsters.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/lovely_snails.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/mavm.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/more-mob-variants.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/more-mobs.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/naturalist.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/promenade.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/snuffles-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/tiny-skeletons.pw.toml"
metafile = true

[[files]]
file = "mods/content/qol/armor-statues.pw.toml"
metafile = true

[[files]]
file = "mods/content/qol/bushier-flowers.pw.toml"
metafile = true

[[files]]
file = "mods/content/qol/etcetera.pw.toml"
metafile = true

[[files]]
file = "mods/content/qol/magnum-torch.pw.toml"
metafile = true

[[files]]
file = "mods/content/qol/mmmmmmmmmmmm.pw.toml"
metafile = true

[[files]]
file = "mods/content/qol/sleep-tight.pw.toml"
metafile = true

[[files]]
file = "mods/content/qol/snowy-spirit.pw.toml"
metafile = true

[[files]]
file = "mods/content/qol/spyglass-astronomy.pw.toml"
metafile = true

[[files]]
file = "mods/content/qol/straw-statues.pw.toml"
metafile = true

[[files]]
file = "mods/content/qol/thigh-highs-etc.pw.toml"
metafile = true

[[files]]
file = "mods/content/silly/moyai.pw.toml"
metafile = true

[[files]]
file = "mods/content/silly/mystical-oak-tree.pw.toml"
metafile = true

[[files]]
file = "mods/content/supplementaries-squared.pw.toml"
metafile = true

[[files]]
file = "mods/crafting-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
metafile = true

[[files]]
file = "mods/dcwa.pw.toml"
metafile = true

[[files]]
file = "mods/deeperdarker.pw.toml"
metafile = true

[[files]]
file = "mods/ding.pw.toml"
metafile = true

[[files]]
file = "mods/double-doors.pw.toml"
metafile = true

[[files]]
file = "mods/ducky-periphs.pw.toml"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
metafile = true

[[files]]
file = "mods/emi/emi-enchanting.pw.toml"
metafile = true

[[files]]
file = "mods/emi/emi-loot.pw.toml"
metafile = true

[[files]]
file = "mods/emi/emi-ores.pw.toml"
metafile = true

[[files]]
file = "mods/emi/emi.pw.toml"
metafile = true

[[files]]
file = "mods/emi/emiffect.pw.toml"
metafile = true

[[files]]
file = "mods/emi/emitrades.pw.toml"
metafile = true

[[files]]
file = "mods/expanded-ecosphere.pw.toml"
metafile = true

[[files]]
file = "mods/extra-mod-integrations.pw.toml"
metafile = true

[[files]]
file = "mods/festive-delight.pw.toml"
metafile = true

[[files]]
file = "mods/fog-looks-good-now-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/friends-and-foes-beekeeper-hut-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa/computer-cartographer.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa/connected-glass.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa/cpmoscc.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa/cpmpvc.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa/custom-player-models.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa/grass-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa/hex-casting.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa/labels.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa/nsmp-discord-bridge.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa/polymorph.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa/polymorphic-energistics.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa/powerae2cc.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa/pv-addon-sculk.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa/seamless-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa/toms-peripherals.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa/verdantvibes.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa/vivecraft-compat.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa/vivecraft.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa2/builtin-servers.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa2/catalogue-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa2/craftpresence.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa2/dark-paintings.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa2/drippy-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa2/fish-on-the-line.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa2/idwtialsimmoedm.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa2/invview.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa2/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/gwaaa2/mouse-wheelie.pw.toml"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/bclib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/cardinal-components-api.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/collective.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/cristel-lib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/dawn.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/iceberg.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/jamlib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/kambrik.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/konkrete.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/library-ferret-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/lithostitched.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/mavapi.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/melody.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/mru.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/paucal.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/paxi.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/pehkui.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/yungs-api.pw.toml"
metafile = true

[[files]]
file = "mods/markdownmanual.pw.toml"
metafile = true

[[files]]
file = "mods/menulogue.pw.toml"
metafile = true

[[files]]
file = "mods/neruina.pw.toml"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
metafile = true

[[files]]
file = "mods/overhauls/betterend.pw.toml"
metafile = true

[[files]]
file = "mods/overhauls/betternether.pw.toml"
metafile = true

[[files]]
file = "mods/overhauls/do-a-barrel-roll.pw.toml"
metafile = true

[[files]]
file = "mods/overhauls/easy-anvils.pw.toml"
metafile = true

[[files]]
file = "mods/overhauls/easy-magic.pw.toml"
metafile = true

[[files]]
file = "mods/overhauls/endrem.pw.toml"
metafile = true

[[files]]
file = "mods/overhauls/structure/yungs-better-desert-temples.pw.toml"
metafile = true

[[files]]
file = "mods/overhauls/structure/yungs-better-end-island.pw.toml"
metafile = true

[[files]]
file = "mods/overhauls/structure/yungs-better-jungle-temples.pw.toml"
metafile = true

[[files]]
file = "mods/overhauls/structure/yungs-better-mineshafts.pw.toml"
metafile = true

[[files]]
file = "mods/overhauls/structure/yungs-better-nether-fortresses.pw.toml"
metafile = true

[[files]]
file = "mods/overhauls/structure/yungs-better-ocean-monuments.pw.toml"
metafile = true

[[files]]
file = "mods/overhauls/structure/yungs-better-strongholds.pw.toml"
metafile = true

[[files]]
file = "mods/overhauls/structure/yungs-better-witch-huts.pw.toml"
metafile = true

[[files]]
file = "mods/overhauls/village/better-village-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/overhauls/village/ct-overhaul-village.pw.toml"
metafile = true

[[files]]
file = "mods/overhauls/village/ctov-beautify-compat.pw.toml"
metafile = true

[[files]]
file = "mods/overhauls/village/ctov-chefs-delight-compat.pw.toml"
metafile = true

[[files]]
file = "mods/overhauls/village/ctov-farmers-delight-compat.pw.toml"
metafile = true

[[files]]
file = "mods/overhauls/village/ctov-friends-and-foes-compat.pw.toml"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/performance/bobby.pw.toml"
metafile = true

[[files]]
file = "mods/performance/chunky.pw.toml"
metafile = true

[[files]]
file = "mods/performance/clumps.pw.toml"
metafile = true

[[files]]
file = "mods/performance/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/performance/fast-paintings.pw.toml"
metafile = true

[[files]]
file = "mods/performance/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/performance/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/performance/indium.pw.toml"
metafile = true

[[files]]
file = "mods/performance/iris.pw.toml"
metafile = true

[[files]]
file = "mods/performance/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/performance/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/performance/memoryleakfix.pw.toml"
metafile = true

[[files]]
file = "mods/performance/moreculling.pw.toml"
metafile = true

[[files]]
file = "mods/performance/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/performance/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/performance/spark.pw.toml"
metafile = true

[[files]]
file = "mods/smooth-chunk-save.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
metafile = true

[[files]]
file = "mods/treechop.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/audio/plasmo-voice.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/audio/presence-footsteps.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/audio/pv-addon-soundphysics.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/audio/sound-physics-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/claims/opac-fabric-create-support.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/claims/open-parties-and-claims.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/block-runner.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/companion.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/crawl.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/cut-through.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/diagonal-fences.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/diagonal-windows.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/goated.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/grass-seeds.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/lootr.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/rightclickharvest.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/snow-under-trees-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/spyglass-improvements.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/advancement-plaques.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/chat-heads.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/highlight.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/jade-addons-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/jade.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/pick-up-notifier.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/status-effect-bars.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/travelers-titles.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/interface/better-advancements.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/interface/better-ping-display-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/interface/better-stats.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/interface/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/interface/fancymenu.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/interface/language-reload.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/interface/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/inventory/distinguished-potions.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/inventory/effect-descriptions.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/inventory/mindful-darkness.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/inventory/norecipebook-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/inventory/shulkerboxtooltip.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/navigation/bluemap.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/navigation/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/navigation/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/other/borderless-mining.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/other/modelfix.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/other/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/other/screenshot-to-clipboard.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/ambient-environment.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/fallingleaves.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/visuality.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
metafile = true
