hash-format = "sha256"

[[files]]
file = "config/openloader/data/villagersplus-promenade-compatability.pw.toml"
metafile = true

[[files]]
file = "config/openloader/data/villagersplus-supplementaries-compatability.pw.toml"
metafile = true

[[files]]
file = "mods/3dskinlayers.pw.toml"
metafile = true

[[files]]
file = "mods/addadd.pw.toml"
metafile = true

[[files]]
file = "mods/additional-blocks-stone-edition.pw.toml"
metafile = true

[[files]]
file = "mods/additional-blocks-vertical-edition.pw.toml"
metafile = true

[[files]]
file = "mods/additional-lanterns.pw.toml"
metafile = true

[[files]]
file = "mods/adorn.pw.toml"
metafile = true

[[files]]
file = "mods/advancement-plaques.pw.toml"
metafile = true

[[files]]
file = "mods/ambient-environment.pw.toml"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
metafile = true

[[files]]
file = "mods/amplified-nether.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/aquamirae.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
metafile = true

[[files]]
file = "mods/automobility.pw.toml"
metafile = true

[[files]]
file = "mods/bclib.pw.toml"
metafile = true

[[files]]
file = "mods/beautify-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
metafile = true

[[files]]
file = "mods/better-animations-collection.pw.toml"
metafile = true

[[files]]
file = "mods/better-lily-pads.pw.toml"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
metafile = true

[[files]]
file = "mods/better-tridents.pw.toml"
metafile = true

[[files]]
file = "mods/betterend.pw.toml"
metafile = true

[[files]]
file = "mods/betternether.pw.toml"
metafile = true

[[files]]
file = "mods/biome-makeover.pw.toml"
metafile = true

[[files]]
file = "mods/bl4cks-sit.pw.toml"
metafile = true

[[files]]
file = "mods/blanket.pw.toml"
metafile = true

[[files]]
file = "mods/blossom-blade.pw.toml"
metafile = true

[[files]]
file = "mods/bluemap-sign-markers.pw.toml"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
metafile = true

[[files]]
file = "mods/bountiful.pw.toml"
metafile = true

[[files]]
file = "mods/bushier-flowers.pw.toml"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/cameraoverhaul.pw.toml"
metafile = true

[[files]]
file = "mods/carpet-fixes.pw.toml"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
metafile = true

[[files]]
file = "mods/carpeted-stairs.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
metafile = true

[[files]]
file = "mods/chefs-delight.pw.toml"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
metafile = true

[[files]]
file = "mods/chunks-fade-in.pw.toml"
metafile = true

[[files]]
file = "mods/cinderscapes.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
metafile = true

[[files]]
file = "mods/clutter.pw.toml"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
metafile = true

[[files]]
file = "mods/companion.pw.toml"
metafile = true

[[files]]
file = "mods/connected-glass.pw.toml"
metafile = true

[[files]]
file = "mods/connectible_chains.pw.toml"
metafile = true

[[files]]
file = "mods/continents.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/couplings.pw.toml"
metafile = true

[[files]]
file = "mods/cozy.pw.toml"
metafile = true

[[files]]
file = "mods/crawl.pw.toml"
metafile = true

[[files]]
file = "mods/create-fabric-sodium-fix.pw.toml"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-mod-trims.pw.toml"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
metafile = true

[[files]]
file = "mods/create-structures.pw.toml"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
metafile = true

[[files]]
file = "mods/creeper-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
metafile = true

[[files]]
file = "mods/croptopia.pw.toml"
metafile = true

[[files]]
file = "mods/ct-overhaul-village.pw.toml"
metafile = true

[[files]]
file = "mods/ctov-beautify-compat.pw.toml"
metafile = true

[[files]]
file = "mods/ctov-chefs-delight-compat.pw.toml"
metafile = true

[[files]]
file = "mods/ctov-croptopia-compat.pw.toml"
metafile = true

[[files]]
file = "mods/ctov-farmers-delight-compat.pw.toml"
metafile = true

[[files]]
file = "mods/ctov-friends-and-foes-compat.pw.toml"
metafile = true

[[files]]
file = "mods/ctov-villagers-plus-compat.pw.toml"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/dawn.pw.toml"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
metafile = true

[[files]]
file = "mods/delightful-froge.pw.toml"
metafile = true

[[files]]
file = "mods/diagonal-fences.pw.toml"
metafile = true

[[files]]
file = "mods/diagonal-windows.pw.toml"
metafile = true

[[files]]
file = "mods/distinguished-potions.pw.toml"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
metafile = true

[[files]]
file = "mods/do-api.pw.toml"
metafile = true

[[files]]
file = "mods/double-doors.pw.toml"
metafile = true

[[files]]
file = "mods/duckling.pw.toml"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
metafile = true

[[files]]
file = "mods/easy-magic.pw.toml"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
metafile = true

[[files]]
file = "mods/elytra-trims.pw.toml"
metafile = true

[[files]]
file = "mods/ender-zoology.pw.toml"
metafile = true

[[files]]
file = "mods/enderman-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/endrem.pw.toml"
metafile = true

[[files]]
file = "mods/ends-delight.pw.toml"
metafile = true

[[files]]
file = "mods/etcetera.pw.toml"
metafile = true

[[files]]
file = "mods/every-compat.pw.toml"
metafile = true

[[files]]
file = "mods/expanded-delight.pw.toml"
metafile = true

[[files]]
file = "mods/expanded-ecosphere.pw.toml"
metafile = true

[[files]]
file = "mods/explorations.pw.toml"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
metafile = true

[[files]]
file = "mods/explosive-enhancement.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-knives.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/festive-delight.pw.toml"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/formations-nether.pw.toml"
metafile = true

[[files]]
file = "mods/formations-overworld.pw.toml"
metafile = true

[[files]]
file = "mods/formations.pw.toml"
metafile = true

[[files]]
file = "mods/friends-and-foes.pw.toml"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
metafile = true

[[files]]
file = "mods/galosphere.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/geophilic.pw.toml"
metafile = true

[[files]]
file = "mods/grass-seeds.pw.toml"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
metafile = true

[[files]]
file = "mods/illager-invasion.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/immersive-structures.pw.toml"
metafile = true

[[files]]
file = "mods/immersivemc.pw.toml"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/jade-addons-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
metafile = true

[[files]]
file = "mods/kambrik.pw.toml"
metafile = true

[[files]]
file = "mods/kiwi.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/leave-my-bars-alone.pw.toml"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
metafile = true

[[files]]
file = "mods/lets-do-bakery.pw.toml"
metafile = true

[[files]]
file = "mods/lets-do-beachparty.pw.toml"
metafile = true

[[files]]
file = "mods/lets-do-candlelight.pw.toml"
metafile = true

[[files]]
file = "mods/lets-do-cheese.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/magnum-torch.pw.toml"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
metafile = true

[[files]]
file = "mods/manic.pw.toml"
metafile = true

[[files]]
file = "mods/mavapi.pw.toml"
metafile = true

[[files]]
file = "mods/mavm.pw.toml"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
metafile = true

[[files]]
file = "mods/mindful-darkness.pw.toml"
metafile = true

[[files]]
file = "mods/mmmmmmmmmmmm.pw.toml"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/moogs-voyager-structures.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/more-mob-variants.pw.toml"
metafile = true

[[files]]
file = "mods/more-mobs.pw.toml"
metafile = true

[[files]]
file = "mods/more-music-discs.pw.toml"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
metafile = true

[[files]]
file = "mods/moyai.pw.toml"
metafile = true

[[files]]
file = "mods/mystical-oak-tree.pw.toml"
metafile = true

[[files]]
file = "mods/nature-arise.pw.toml"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
metafile = true

[[files]]
file = "mods/natures-spirit.pw.toml"
metafile = true

[[files]]
file = "mods/nightlights.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/norecipebook-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/not-just-biomes.pw.toml"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
metafile = true

[[files]]
file = "mods/obscure-api.pw.toml"
metafile = true

[[files]]
file = "mods/opac-fabric-create-support.pw.toml"
metafile = true

[[files]]
file = "mods/open-loader.pw.toml"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
metafile = true

[[files]]
file = "mods/overweight-farming.pw.toml"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/physicsmod.pw.toml"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
metafile = true

[[files]]
file = "mods/plasmo-voice.pw.toml"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
metafile = true

[[files]]
file = "mods/profundis.pw.toml"
metafile = true

[[files]]
file = "mods/promenade.pw.toml"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/pv-addon-soundphysics.pw.toml"
metafile = true

[[files]]
file = "mods/rechiseled-create.pw.toml"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/regions-unexplored.pw.toml"
metafile = true

[[files]]
file = "mods/repurposed-structures-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
metafile = true

[[files]]
file = "mods/river-redux.pw.toml"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
metafile = true

[[files]]
file = "mods/simple-trims.pw.toml"
metafile = true

[[files]]
file = "mods/sleep-tight.pw.toml"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
metafile = true

[[files]]
file = "mods/snow-real-magic.pw.toml"
metafile = true

[[files]]
file = "mods/snow-under-trees-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/snuffles-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/species.pw.toml"
metafile = true

[[files]]
file = "mods/spell-power.pw.toml"
metafile = true

[[files]]
file = "mods/spelunkery.pw.toml"
metafile = true

[[files]]
file = "mods/sprout.pw.toml"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
metafile = true

[[files]]
file = "mods/stellarity.pw.toml"
metafile = true

[[files]]
file = "mods/stoneworks.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries-squared.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
metafile = true

[[files]]
file = "mods/terrestria.pw.toml"
metafile = true

[[files]]
file = "mods/thigh-highs-etc.pw.toml"
metafile = true

[[files]]
file = "mods/this-rocks.pw.toml"
metafile = true

[[files]]
file = "mods/tidal-towns.pw.toml"
metafile = true

[[files]]
file = "mods/tiny-skeletons.pw.toml"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
metafile = true

[[files]]
file = "mods/trading-post.pw.toml"
metafile = true

[[files]]
file = "mods/travelers-titles.pw.toml"
metafile = true

[[files]]
file = "mods/traverse.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/twigs.pw.toml"
metafile = true

[[files]]
file = "mods/vanilla-refresh.pw.toml"
metafile = true

[[files]]
file = "mods/villagersplus.pw.toml"
metafile = true

[[files]]
file = "mods/vinery.pw.toml"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
metafile = true

[[files]]
file = "mods/vivecraft.pw.toml"
metafile = true

[[files]]
file = "mods/wakes.pw.toml"
metafile = true

[[files]]
file = "mods/wdmgslt.pw.toml"
metafile = true

[[files]]
file = "mods/wilder-wild.pw.toml"
metafile = true

[[files]]
file = "mods/windchimes.pw.toml"
metafile = true

[[files]]
file = "mods/wwoo.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yeetus-experimentus.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
metafile = true
