hash-format = "sha256"

[[files]]
file = "mods/content/blocks/chipped.pw.toml"
metafile = true

[[files]]
file = "mods/content/compat/create-compat-betterend-betternether.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/custom/nsmp-bridge.pw.toml"
metafile = true

[[files]]
file = "mods/custom/nsmp-restarter.pw.toml"
metafile = true

[[files]]
file = "mods/custom/nsmp-spawner.pw.toml"
metafile = true

[[files]]
file = "mods/custom/nsmp-structurefix.pw.toml"
metafile = true

[[files]]
file = "mods/custom/nsmp-worldgen.pw.toml"
metafile = true

[[files]]
file = "mods/custom/nsmp-worldtest.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/athena-ctm.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/bclib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/konkrete.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/melody.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/performance/indium.pw.toml"
metafile = true

[[files]]
file = "mods/performance/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/emi/emi.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/ui/auth-me.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/ui/fancymenu.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/ui/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/effective.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/iris.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/end/betterend.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/end/nullscape.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/quadral.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/rethinking-voxels.pw.toml"
metafile = true
