hash-format = "sha256"

[[files]]
file = "bluemap/postgresql.pw.toml"
metafile = true

[[files]]
file = "config/bclib/client.json"

[[files]]
file = "config/bclib/main.json"

[[files]]
file = "config/bclib/server.json"

[[files]]
file = "config/builtinservers.json"

[[files]]
file = "config/collective/checked.txt"

[[files]]
file = "config/expanded_ecosphere/config.json5"

[[files]]
file = "config/expanded_ecosphere/replace_biomes.json5"

[[files]]
file = "config/fancymenu/assets/logo.png"

[[files]]
file = "config/fancymenu/customizablemenus.txt"

[[files]]
file = "config/fancymenu/customization/drippy_loading_overlay_layout.txt"

[[files]]
file = "config/fancymenu/customization/options_screen_layout.txt"

[[files]]
file = "config/fancymenu/customization/title_screen_layout.txt"

[[files]]
file = "config/fancymenu/minecraftwindow/icons/icon16x16.png"

[[files]]
file = "config/fancymenu/minecraftwindow/icons/icon32x32.png"

[[files]]
file = "config/fancymenu/options.txt"

[[files]]
file = "config/paxi/datapacks/nsmp-datapack.pw.toml"
metafile = true

[[files]]
file = "config/paxi/resourcepacks/nsmp-resourcepack.pw.toml"
metafile = true

[[files]]
file = "config/supplementaries-common.json"

[[files]]
file = "config/tectonic.json"

[[files]]
file = "mods/content/applied-energistics/ae2-qol-recipes.pw.toml"
metafile = true

[[files]]
file = "mods/content/applied-energistics/ae2.pw.toml"
metafile = true

[[files]]
file = "mods/content/applied-energistics/applied-energistics-2-wireless-terminals.pw.toml"
metafile = true

[[files]]
file = "mods/content/applied-energistics/mega.pw.toml"
metafile = true

[[files]]
file = "mods/content/blocks/chipped.pw.toml"
metafile = true

[[files]]
file = "mods/content/compat/ae2-emi-crafting.pw.toml"
metafile = true

[[files]]
file = "mods/content/compat/cccbridge.pw.toml"
metafile = true

[[files]]
file = "mods/content/compat/create-compat-betterend-betternether.pw.toml"
metafile = true

[[files]]
file = "mods/content/compat/polymorphic-energistics.pw.toml"
metafile = true

[[files]]
file = "mods/content/computer-craft/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/content/computer-craft/computer-cartographer.pw.toml"
metafile = true

[[files]]
file = "mods/content/computer-craft/ducky-periphs.pw.toml"
metafile = true

[[files]]
file = "mods/content/computer-craft/plethora-peripherals.pw.toml"
metafile = true

[[files]]
file = "mods/content/computer-craft/toms-peripherals.pw.toml"
metafile = true

[[files]]
file = "mods/content/computer-craft/unlimitedperipheralworks.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/content/decor/miku-plushies.pw.toml"
metafile = true

[[files]]
file = "mods/content/exposure.pw.toml"
metafile = true

[[files]]
file = "mods/content/farmers-delight/crate-delight.pw.toml"
metafile = true

[[files]]
file = "mods/content/farmers-delight/cultural-delights-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/content/farmers-delight/ends-delight.pw.toml"
metafile = true

[[files]]
file = "mods/content/farmers-delight/expanded-delight.pw.toml"
metafile = true

[[files]]
file = "mods/content/farmers-delight/farmers-delight-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/content/farmers-delight/frights-delight.pw.toml"
metafile = true

[[files]]
file = "mods/content/farmers-delight/more-delight.pw.toml"
metafile = true

[[files]]
file = "mods/content/farmers-delight/nethers-delight-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/content/farmers-delight/oceans-delight.pw.toml"
metafile = true

[[files]]
file = "mods/content/farmers-delight/ubes-delight.pw.toml"
metafile = true

[[files]]
file = "mods/content/hexcasting/hexcasting.pw.toml"
metafile = true

[[files]]
file = "mods/content/hexcasting/hexdim.pw.toml"
metafile = true

[[files]]
file = "mods/content/mighty-mail-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/creeper-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/enderman-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/species.pw.toml"
metafile = true

[[files]]
file = "mods/content/pick-your-poison.pw.toml"
metafile = true

[[files]]
file = "mods/content/silly/autism.pw.toml"
metafile = true

[[files]]
file = "mods/content/silly/moyai.pw.toml"
metafile = true

[[files]]
file = "mods/content/silly/mystical-oak-tree.pw.toml"
metafile = true

[[files]]
file = "mods/content/silly/pipe-bomb-in-the-mail.pw.toml"
metafile = true

[[files]]
file = "mods/content/supplementaries/amendments.pw.toml"
metafile = true

[[files]]
file = "mods/content/supplementaries/supplementaries-squared.pw.toml"
metafile = true

[[files]]
file = "mods/content/supplementaries/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/custom/nsmp-bridge.pw.toml"
metafile = true

[[files]]
file = "mods/custom/nsmp-restarter.pw.toml"
metafile = true

[[files]]
file = "mods/custom/nsmp-spawner.pw.toml"
metafile = true

[[files]]
file = "mods/custom/nsmp-structurefix.pw.toml"
metafile = true

[[files]]
file = "mods/custom/nsmp-worldgen.pw.toml"
metafile = true

[[files]]
file = "mods/custom/nsmp-worldtest.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/athena-ctm.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/balm.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/bclib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/collective.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/cristel-lib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/framework-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/fzzy-config.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/kiwi.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/konkrete.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/melody.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/mru.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/owo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/paucal.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/paxi.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/peripheralium.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/satin-api.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/sushi-bar.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/tcdcommons.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/yungs-api.pw.toml"
metafile = true

[[files]]
file = "mods/performance/async-locator.pw.toml"
metafile = true

[[files]]
file = "mods/performance/bobby.pw.toml"
metafile = true

[[files]]
file = "mods/performance/c2me-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/performance/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/performance/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/performance/gputape.pw.toml"
metafile = true

[[files]]
file = "mods/performance/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/performance/indium.pw.toml"
metafile = true

[[files]]
file = "mods/performance/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/performance/language-reload.pw.toml"
metafile = true

[[files]]
file = "mods/performance/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/performance/memoryleakfix.pw.toml"
metafile = true

[[files]]
file = "mods/performance/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/performance/moreculling.pw.toml"
metafile = true

[[files]]
file = "mods/performance/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/performance/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/performance/vmp-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/testing/antique-atlas-4.pw.toml"
metafile = true

[[files]]
file = "mods/testing/explosive-enhancement.pw.toml"
metafile = true

[[files]]
file = "mods/testing/spice-of-life-valheim-edition.pw.toml"
metafile = true

[[files]]
file = "mods/testing/surveyor.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/audio/dynamicsurroundingsfabric.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/audio/presence-footsteps.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/audio/sound.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/emi/emi-loot.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/emi/emi-ores.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/emi/emi.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/emi/emienchants.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/emi/emiffect.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/emi/emitrades.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/emi/extra-mod-integrations.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/connectiblechains.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/diagonal-fences.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/diagonal-walls.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/diagonal-windows.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/grass-seeds.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/ironfish.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/lootr.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/netherportalfix.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/passable-foliage.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/screenshot-to-clipboard.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/skippy-pearls.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/softer-hay-bales.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/treechop.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/unloaded-activity.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/better-advancements.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/better-stats.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/bettersmithingtable.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/borderless-mining.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/easy-anvils.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/easy-magic.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/norecipebook.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/patchoulibutton.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/polymorph.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/tooltipfix.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/chat-heads.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/jade-addons-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/jade.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/modelfix.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/overflowing-bars.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/status-effect-bars.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/auth-me.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/builtin-servers.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/disable-accessibility-screen.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/drippy-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/fancymenu.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/seamless-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/ambient-environment.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/distanthorizons.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/distinguished-potions.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/highlight.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/iris.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/particular.pw.toml"
metafile = true

[[files]]
file = "mods/utilities/bluemap/bluemap-offline-player-markers-(fabric).pw.toml"
metafile = true

[[files]]
file = "mods/utilities/bluemap/bluemap.pw.toml"
metafile = true

[[files]]
file = "mods/utilities/chunky.pw.toml"
metafile = true

[[files]]
file = "mods/utilities/invview.pw.toml"
metafile = true

[[files]]
file = "mods/utilities/spark.pw.toml"
metafile = true

[[files]]
file = "mods/utilities/world-preview.pw.toml"
metafile = true

[[files]]
file = "mods/utilities/worldedit.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/end/betterend.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/end/nullscape.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/nether/amplified-nether.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/nether/betternether.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/overworld/expanded-ecosphere.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/overworld/ribbits.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/overworld/tectonic.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/quadral.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/rethinking-voxels.pw.toml"
metafile = true
