name = "neko.mc"
author = "Atakku"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3ef895f7d083602e4358228c6354a1a7211b38958e0158ec2aa86cf1a63f0ac"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
