name = "neko.mc"
author = "Atakku"
version = "1.0.25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86da48315d8e3467824eec547cb3f2428d6094f1e1156a758121a4752be36bed"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
