name = "neko.mc"
author = "Atakku"
version = "1.0.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c0efa139af179e2e5f8363076e5aee784725fcf0d05b9bf9424928a9d8c5d65"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
