name = "neko.smp"
author = "Atakku"
version = "1.4.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "922da7035b73791032ff02cf5b141b51f6395236bf9a7499daa74e26823a9080"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
