name = "neko.smp"
author = "Atakku"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebecdcbebdd399a223996a2167d26d26c9191988e5887218722cf0dd198adfe6"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
