name = "neko.mc"
author = "Atakku"
version = "1.0.38"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a9c2d58b81d3b709e338db32b9456e879b563cdd56f67a19377ce346740cd87"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
