name = "neko.smp"
author = "Atakku"
version = "1.5.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0165a16b6609af5fd6eee8d715a773f121cfe31aaa4f6c0a82252a34fb7a99de"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
