name = "neko.mc"
author = "Atakku"
version = "1.0.39"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f4aa81947e94f59e28d2d6a47dd606fe56ea6f560609807b2afab1929ded06b"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
