name = "neko.mc"
author = "Atakku"
version = "1.0.29"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4294410273b9aecdfd6266a9bfdb6c47cfc4573691dd6fca49d7e208e3a4d864"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
