name = "neko.smp"
author = "Atakku"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db41d844dcf19a67e336004acb1ed9d3f74b18b472fd3e91568ab2e8c318833a"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
