name = "neko.mc"
author = "Atakku"
version = "1.0.35"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f7181ed5d8651cda0a7d022758a9c1e67f632af52c14b2f7d240da6495cbf1b"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
