name = "neko.mc"
author = "Atakku"
version = "0.3.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d7d7c98525e36586d3a2fae49289af6a4405e1a5c8a7d48a5728066c8508b55"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
