name = "neko.mc"
author = "Atakku"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6306dd4193c4a9c07c2348c18e6d92fb1b727624bc0d57494e6340ed146d149b"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
