name = "neko.mc"
author = "Atakku"
version = "0.3.17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2eedfc6db924d954b4497f64b8c462809976ef98486883906d03537d80a7b042"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
