name = "neko.mc"
author = "Atakku"
version = "1.0.30"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3ce6efd677c61235deb427b039dcfd199c3b63d229b514263c406cf6719e658"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
