name = "neko.mc"
author = "Atakku"
version = "0.3.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5890536e65a1e7abed57178c3bdbb159c71d2bd487d37081ab74274485c7ef0d"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
