name = "neko.mc"
author = "Atakku"
version = "1.0.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62a24bfac71c03c69c31165321368dff4b65367aa020fa81004a9e17a5615f48"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
