name = "neko.smp"
author = "Atakku"
version = "1.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cf81bd9f2a163d47c84dde9ee44c5a0969f4a5d842d31f4327f07006be282db"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
