name = "neko.smp"
author = "Atakku"
version = "1.5.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db4f5e240d903a444fdce8beb53ba77da45f2e0d548c517c5d31405b1ad90b54"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
