name = "neko.smp"
author = "Atakku"
version = "1.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e19776ba899369d4faf0634a1cacb1a9c901f427bb7631d0f5b878a477f6030b"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
