name = "neko.smp"
author = "Atakku"
version = "1.9.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f49f448fc5963c2ccad1650e28f604c42ee62a80bcf74ac56d5a00f25385782"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
