name = "neko.smp"
author = "Atakku"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9edb0711e3095044a5d7d356af434ce8ed158c20be724a478b51ab9c840af95"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
