name = "neko.smp"
author = "Atakku"
version = "1.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8bafeed29330021578c5055ada5b8a074dd9869f3d3218c49f825d62f26ebec"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
