name = "neko.mc"
author = "Atakku"
version = "1.0.32"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8a8792ca518f1e944cba0f5fd775dbd6faf0b815321edec676187475fb74402"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
