name = "neko.mc"
author = "Atakku"
version = "1.0.37"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86cfd7220d444fb45c17a3efef635ce6e74a6256788773c712b7374e9bc9628b"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
