name = "neko.mc"
author = "Atakku"
version = "1.0.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13e5750c1ec3a504b35b26d11d09a9ba8792b490c9e8ed01bd6337878fe6d0e2"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
