name = "neko.smp"
author = "Atakku"
version = "1.5.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a51413ae56da3f7104428d1903e1b21c36f835db9a548a2b64a844f19952be2"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
