name = "neko.mc"
author = "Atakku"
version = "1.0.33"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c3f2f3abdde0b2f21b7838587befad9b42d7763310aec35b48f1132fcf48844"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
