name = "neko.mc"
author = "Atakku"
version = "0.3.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "258f64d1411f2bf6c47ab1bfc140e2935c9f0001db252c64798b4ba107302d78"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
