name = "neko.mc"
author = "Atakku"
version = "1.0.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "233dcb2ce0dea7863fae79af6133c1040d6b6363897f652cdbb30c15c4985b49"

[versions]
fabric = "0.14.18"
minecraft = "1.19.2"
