name = "neko.mc"
author = "Atakku"
version = "1.0.26"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b23bd76b7cefe367bb9066e6176be538cfee12e24462ba851cecee398aa1bdd"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
