[kinetics]
	[kinetics.contraptions]
		maxRopeLength = 638
[schematics]
	maxSchematics = 32
	maxTotalSchematicSize = 1024
	maxSchematicPacketSize = 1024
[trains]
	maxTrackPlacementLength = 64
	maxAssemblyLength = 128
	[trains.trainStats]
		trainTopSpeed = 45.0
		trainTurningTopSpeed = 45.0
		trainAcceleration = 3.0
	[trains.poweredTrainStats]
		poweredTrainTopSpeed = 80.0
		poweredTrainTurningTopSpeed = 80.0
		poweredTrainAcceleration = 3.0
