name = "fsmp-nbg"
filename = "fsmp-bridge-0.1.1+1.20.1-server.jar"
side = "server"

[download]
url = "https://github.com/Atakku/fsmp-nbg/releases/download/mc1.20.1/v0.1.1/fsmp-bridge-0.1.1%2B1.20.1-server.jar"
hash-format = "sha256"
hash = "ce435c969956be93d45208e851cd386349092b24882476914153a51d06c27c0a"

[update]
[update.github]
branch = "1.20.1"
regex = "^.+(?<!-api|-dev|-dev-preshadow|-sources)\\.jar$"
slug = "Atakku/fsmp-nbg"
tag = "mc1.20.1/v0.1.1"
